prjgenesis/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('status/', include('status.urls')),
    path('userm/',include('userm.urls')),
    path('shop/', include('shop.urls')),
    path('', views.redirect_status)
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = "shop" 
urlpatterns = [
    path('', views.index, name='index'),
    path('list/<str:category_slug>/', views.product_list, name='list'),
    path('detail/<int:id>/<str:slug>/', views.product_detail, name="detail"),
    path('payment/<int:id>/<str:slug>/', views.payment, name="payment"),
    path('success/', views.success, name="success"),
    path('search/', views.search, name='search'),
]

status/urls.py
from django.urls import path, include
from . import views

app_name = 'status'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/', views.send, name='post'),
    path('users/<str:username>/', views.user, name='user'),
    path('details/<int:no>/', views.details, name='details'),
    path('replyto/<int:no>/',views.replyto, name='replyto'),
    path('like/<int:id>/', views.like, name='like'),
    path('unlike/<int:id>/', views.unlike, name='unlike'),
    path('contact/', views.contact, name='contact'),
    path('feed/', views.feed, name='feed'),
    path('search/', views.search, name='search'),
    path('help/',views.help, name='help')
]

userm/urls.py
from django.urls import path

from . import views

app_name="user"
urlpatterns = [
    path('login/',views.user_login, name='login'),
    path('signup/', views.user_signup, name='signup'),
    path('user/<str:username>', views.user_details, name='user'),
    path('edit/', views.edit_user, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('friend/<str:user>/<str:user2>', views.friend, name='friend'),
    path('unfriend/<str:user>/<str:user2>', views.unfriend, name='unfriend'),
]

status/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    body = models.TextField(max_length=200)
    likes = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published', null=True)
    def __str__(self):
        return self.title

class Reply(models.Model):
    class Meta:
        verbose_name_plural = "replies"
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.CharField(max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.text

status/forms.py
from django import forms
from .models import Post,Reply

class StatusForm(forms.Form):
    title = forms.CharField()
    body = forms.CharField(widget=forms.Textarea)

class ReplyForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)

status/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.template import loader
from django.contrib import messages
from django.utils import timezone
from django.db.models.query import QuerySet
from django.db.models import F, Count
from django.contrib.auth.models import User
from urllib.parse import urlencode
from django.contrib.auth.decorators import login_required
from django import forms
from .models import *
from shop.models import Item
from userm.models import UserExtendedR
from .forms import StatusForm,ReplyForm
from .models import Post,Reply

def index(request):
    if request.method == 'POST':
        if search_handle(request):
            print("Reaching here!")
            return search_handle(request)
    template = loader.get_template('status/index.html')
    if request.user.is_authenticated:
        user = request.user
    else:
        user = None
    context = {
        'user': user
    }
    return HttpResponse(template.render(context, request))

def search_handle(r):
    if 'searchb' in r.POST:
        text = r.POST['text']
        typ = r.POST['type']
        if text != "": 
            base_url = reverse('status:search')
            query_string = urlencode({'type': typ,'name': text })
            return redirect("{}?{}".format(base_url, query_string))
    return False

@login_required(login_url='/userm/login')
def send(request):
    print(str(request.user))
    if request.method == 'POST':
        if not search_handle(request):
            print("Reached here!")
            form = StatusForm(request.POST)
            if request.user.is_authenticated:
                if form.is_valid():
                    cd = form.cleaned_data
                    if cd['title'] != "" and cd['body'] != "":
                        status = Post(user=request.user,title=cd['title'],body=cd['body'],pub_date=timezone.now())
                        status.save()
                        return HttpResponseRedirect(reverse('status:index'))
                    else:
                        messages.info(request,message="No fields must be empty")
            else:
                return HttpResponse("You must be logged in to perform this action!")
        else:
            return search_handle(request)
    else:
        form = StatusForm()
    context = {
        'form' : form,
        'user' : request.user
    }
    return render(request, 'status/send.html', context)

def user(request, username):
    if request.method == 'POST':
        if search_handle(request):
            return search_handle(request)
    try:
        user = UserExtendedR.objects.get(username=username)
    except(KeyError, UserExtendedR.DoesNotExist):
        return HttpResponse("The user does not exist!")
    else :
        posts = user.post_set.order_by('-pub_date')
        template = loader.get_template('status/user.html')
        context = {
            'user' : user,
            'posts' : posts
        }
        return HttpResponse(template.render(context, request))

def details(request, no):
    if request.method == 'POST':
        if search_handle(request):
            return search_handle(request)
    try:
        post = Post.objects.get(pk=no)
    except(KeyError, Post.DoesNotExist):
        return HttpResponse("The Post does not exist!")
    else:
        template = loader.get_template('status/details.html')
        context = {
            'post': post,
            'user': request.user
        }
        return HttpResponse(template.render(context, request))

@login_required(login_url='/userm/login')
def replyto(request, no):
    if request.user.is_authenticated:
        try:
            post = Post.objects.get(pk=no)
        except(KeyError, Post.DoesNotExist ):
            return HttpResponse("The Post does not exist!")
        if request.method == 'POST':
            if not search_handle(request):
                form = ReplyForm(request.POST)
                if form.is_valid():
                    cd = form.cleaned_data
                    if cd['text'] != "":
                        reply = Reply(user = request.user, text=cd['text'], post=post)
                        reply.save()
                        return redirect('status:details', no=no)
                    else:
                        return HttpResponse("The Text Field cannot be empty")
            else:
                return search_handle(request)
        else:
            form = ReplyForm()
    else:
        return HttpResponse("You have to be logged in to perform the action!")
    context = {
        'form': form,
        'post': post,
        'user': request.user
    }
    return render(request, 'status/replyto.html', context=context)

@login_required(login_url='/userm/login')
def feed(request):
    if request.method == 'POST':
        if search_handle(request):
            return search_handle(request)
    if request.user.is_authenticated:
        lst = Post.objects.none()
        for user in request.user.following.all():
            print(user)
            lst = lst | user.post_set.all()
        lst = lst.distinct().order_by('-pub_date')
        context = {
            'user': request.user,
            'list': lst
        }
        return render(request, 'status/feed.html', context=context)
    else:
        return HttpResponse('You must be logged in to do that!')

@login_required(login_url='/userm/login')
def like(request, id):
    try:
        post = Post.objects.get(pk=id)
    except(KeyError, Post.DoesNotExist):
        return HttpResponse('Post does not exist')
    else:
        if request.user.is_authenticated:
            post.likes += 1
            post.save()
            request.user.post_liked.add(post)
            request.user.save()
        else:
            return HttpResponse('You have to be logged in to do this!')
    return redirect('status:details', id)

@login_required(login_url='/userm/login')
def unlike(request,id):
    try:
        post = Post.objects.get(pk=id)
    except(KeyError, Post.DoesNotExist):
        return HttpResponse('Post does not exist')
    else:
        if request.user.is_authenticated:
            post.likes -= 1
            post.save()
            request.user.post_liked.remove(post)
            request.user.save()
        else:
            return HttpResponse('You have to be logged in to do this!')
    return redirect('status:details', id)

def search(request):
    if request.method == 'POST':
        if search_handle(request):
            return search_handle(request)
    if request.method == 'GET' and 'type' in request.GET and 'name' in request.GET:
        search_type = request.GET.get('type', None)
        search_option = request.GET.get('name', None)
        print(search_type)
        print(search_option)
        if (search_type == '1'):        
            users = UserExtendedR.objects.filter(username__icontains=search_option).annotate(count=Count('user_from_set')).order_by('-count')
            context = {
                'users': users,
                'user': request.user
            }
        elif(search_type == '2'):
            posts = Post.objects.filter(body__icontains=search_option, title__icontains=search_option).order_by('-likes')
            context = {
                'posts': posts,
                'user': request.user 
            }
        elif(search_type == '3'):
            items = Item.objects.filter(name__icontains=search_option)
            context = {
                'items': items,
                'user': request.user
            }
        else:
            return HttpResponseNotFound('This search type does not exist')
    else:
        context = {
            'user': request.user
        }
    return render(request, 'status/search.html', context=context)

def help(request):
    if request.method == 'GET' and 'type' in request.GET and 'name' in request.GET:
        pass

def contact(request):
    if request.method == 'POST':
        if search_handle(request):
            return search_handle(request)
    return render(request, 'status/contact.html')

status/templates/status/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" href="{% static 'shop/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/open-iconic-bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/open-iconic-bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/open-iconic.css' %}">
        <link rel="stylesheet" href="{% static 'shop/font.css' %}">
        <link rel="stylesheet" href="{% static 'shop/main.css' %}">
        <script src="{% static 'shop/bootstrap.min.js' %}"></script>
        {% block imports %} {% endblock imports%}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <div class="page-header">
            <h1 style="display:inline;"><a href="{% url 'status:index' %}">Project Genesis</a></h1>
            <form action="." method="post" autocomplete="off" onsubmit="validate()" name="search">
                {% csrf_token %}
                <div class="form-row align-items-center justify-content-center" style="font-family: 'Blinker', sans-serif;">
                    <div class="col-md-6">
                        <input type="text" class="form-control" placeholder="Search for people, feeds etc." name="text">
                    </div>
                    <div class="col-auto">
                        <select class="custom-select custom-select" name="type">
                            <option selected value="1">People</option>
                            <option value="2">Posts</option>
                        </select>
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-outline-dark btn-dark" name="searchb">
                            Search <span class="oi oi-magnifying-glass" title="icon magnifying-glass" aria-hidden="true"></span>
                        </button>
                    </div>
                </div></div>
            </form>
        </div>
        {% block navbar %}
            <nav class="navbar navbar-expand-md navbar-dark" style="background-color:rgb(91, 90, 95);">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Edit Profile</a></li>
                        {% endif %}
                        {% if user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                        {% else %}  
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        {% endblock navbar %}
         <div class="content container">
            <div class="row">
                <div class="col-md-10">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

status/templates/status/contact.html
{% extends "status/base.html" %}
{% load static %}

{% block title %}Project Genesis/ Contact Us{% endblock title %}

{% block imports %}
    <link rel="stylesheet" href="{% static 'status/contact.css' %}" >
{% endblock imports %}

{% block navbar %}
            <nav class="navbar navbar-expand-md navbar-dark" style="background-color:rgb(91, 90, 95);">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Edit Profile</a></li>
                        {% endif %}
                        {% if user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                        {% else %}  
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        {% endblock navbar %}

{% block content %}
    <h1 class="title">Contact Us:</h1>
    <p>If you want your product to appear here, you may use the following methods to try and contact us. The Project Genesis Team will add your item after verifying it.:</p>
    <p>Email: interested@prjgenesis.com</p>
    <p>Telephone: 98410-00000</p>
{% endblock content %}

status/templates/status/details.html
{% extends "status/base.html" %}
{% load static %}
{% load userfil %}

{% block title %}Project Genesis/Status{% endblock title %}

{% block imports %}
    <link rel="stylesheet" href="{% static 'status/details.css' %}">
{% endblock imports %}

{% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Profile</a></li>
                {% endif %}
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                {% else %}  
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock navbar %}

{% block content %}
    <h1 class="det-title"> {{ post.title }}</h1>
    <div class="det-body">{{post.body | linebreaksbr}}<br /><p align="right">By <a href="{% url 'user:user' post.user.username %}">{{post.user.username}}</a></p></div>
    <a href="{% url 'status:replyto' post.pk %}" class="btn btn-custom" role="button">Reply</a>
    {% if user.is_authenticated %}
        {% if user|get_post_if_liked_by_user:post %}
            <div class="like active">{{ post.likes }}<a href="{% url 'status:unlike' post.pk %}"><span class="oi oi-heart" title="icon heart" aria-hidden="true"></span></a></div>
        {% else %}
            <div class="like">{{ post.likes }}<a href="{% url 'status:like' post.pk %}"><span class="oi oi-heart" title="icon heart" aria-hidden="true"></span></a></div>
        {% endif %}
    {% endif %}
    {% if post.reply_set.all.first %}
    <ul>
    {% for reply in post.reply_set.all %}
        <div class="det-reply"><li><a href="{% url 'user:user' reply.user %}">{{ reply.user }}</a> - {{ reply.text }}</div>
    {% endfor %}
    </ul>
    {% endif %}
{% endblock content %}

status/templates/status/feed.html
{% extends "status/base.html" %}
{% load static %}

{% block title %}Project Genesis/Status{% endblock title %}

{% block imports %}
    <link rel="stylesheet" href="{% static 'status/user.css' %}">
{% endblock imports %}

{% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark" style="background-color:rgb(91, 90, 95);">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                </li>
            <li class="nav-item active">
                    <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Edit Profile</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                {% else %}  
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock navbar %}

{% block content %}
<h1>Status Feed</h1>
    <p>Here you can view the statuses from the people you follow. To know how to follow people click <a href="#" style="color:purple;">here</a>.</p>
<ul class="background">
    {% for l in list %}
        <li><a href="{% url 'status:details' l.pk %}" class="list">{{ l.user.username }} - {{ l.title }}</a>
    {% endfor %}
</ul>
{% endblock content %}

status/templates/status/index.html
{% extends "status/base.html" %}
{% load static %}

{% block title %}Project Genesis/Status{% endblock title %}</title>

{% block imports %}
    <link rel="stylesheet" href="{% static 'status/index.css' %}">
{% endblock imports %}

{% block content %}
    {% if user.is_authenticated %}
        <h1 class="title">Hello, {{ user.username }}</h1>
    {% else %}
        <h1 class="title">Hello</h1>
    {% endif %}
    <p style="font-size:1.1em;padding-bottom:10px;">Hello and welcome to our index page of Project Genesis.</p>
    <p style="font-size:1.1em;padding-bottom:10px;">This website allows you to sell merchandise and tell fans about any discounts or extra item you are selling
    This way you can get our message out saying you <b>are</b> selling something and sell it here at the same time.</p>
    {% if user %}
        <a href="{% url 'status:post' %}" class="index"> Post a Status</a> <br>
        <a href="{% url 'user:user' user %}" class="index"> Visit your page</a>
    {% else %}
        <a href="{% url 'user:login' %}" class="index">Login</a>
    {% endif %}
    <br><br><br><br><br>
    <p style="font-size:1.1em;padding-bottom:10px;">If you are interested in selling your products, <a href="{% url 'status:contact' %}">click here</a></p>
{% endblock content %}

status/templates/status/search.html
{% extends "status/base.html" %}
{% load static %}
{% load userfil %}

{% block imports %}
    <link rel="stylesheet" href="{% static 'status/user.css' %}">
{% endblock imports %}

{% block title %}Search Results{% endblock title %}

{% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark" style="background-color:rgb(91, 90, 95);">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Profile</a></li>
                {% endif %}
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                {% else %}  
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock navbar %}

{% block content %}
    {% if posts or users %}
        <h1 class="title">Search Resuts</h1>
    {% else %}
        <h1 class="title">We couldn't find matching results.</h1>
    {% endif %} 
    <div class="results">
        <ul class="background">
            {% if posts %}
                {% for post in posts %}
                    <li><a href="{% url 'status:details' post.pk %}" class="list">{{post.user.username}} - {{post.title}}</a></li>
                {% endfor %}
            {% elif users%}
                {% for u in users %}
                    <div class="user">
                        <li><a href="{% url 'user:user' u.username %}"><img class="image" src="{% if u.avatar %}{{ u.avatar.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="{{u.username}}"></a>
                        <a href="{% url 'user:user' u.username %}" class="list2">{{u.username}}</a>
                        <span style="float:right;font-size:1.2em;">{{u|count}} follower{{u|count|pluralize}}</span>
                        </li>
                    </div>
                {% endfor %}
            {% else %}
                <p style="font-size:1.3em;padding-bottom:10px;">We couldn't find any matching results, please check the spelling and try again</p>          
            {% endif %}
        </ul>
    </div>
{% endblock content %}