prjgenesis/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('status/', include('status.urls')),
    path('userm/',include('userm.urls')),
    path('shop/', include('shop.urls')),
    path('', views.redirect_status)
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = "shop" 
urlpatterns = [
    path('', views.index, name='index'),
    path('list/<str:category_slug>/', views.product_list, name='list'),
    path('detail/<int:id>/<str:slug>/', views.product_detail, name="detail"),
    path('payment/<int:id>/<str:slug>/', views.payment, name="payment"),
    path('success/', views.success, name="success"),
    path('search/', views.search, name='search'),
]

status/urls.py
from django.urls import path, include
from . import views

app_name = 'status'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/', views.send, name='post'),
    path('users/<str:username>/', views.user, name='user'),
    path('details/<int:no>/', views.details, name='details'),
    path('replyto/<int:no>/',views.replyto, name='replyto'),
    path('like/<int:id>/', views.like, name='like'),
    path('unlike/<int:id>/', views.unlike, name='unlike'),
    path('contact/', views.contact, name='contact'),
    path('feed/', views.feed, name='feed'),
    path('search/', views.search, name='search'),
    path('help/',views.help, name='help')
]

userm/urls.py
from django.urls import path

from . import views

app_name="user"
urlpatterns = [
    path('login/',views.user_login, name='login'),
    path('signup/', views.user_signup, name='signup'),
    path('user/<str:username>', views.user_details, name='user'),
    path('edit/', views.edit_user, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('friend/<str:user>/<str:user2>', views.friend, name='friend'),
    path('unfriend/<str:user>/<str:user2>', views.unfriend, name='unfriend'),
]

userm/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

class FollowContact(models.Model):
    class Meta:
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"
        ordering = ('-created',)

    user_from = models.ForeignKey('userm.UserExtendedR', related_name="user_from_set", on_delete=models.CASCADE)
    user_to= models.ForeignKey('userm.UserExtendedR', related_name="user_to_set", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    def __str__(self):
        return self.user_from.username + " follows " + self.user_to.username

class UserExtendedManager(BaseUserManager):
    def create_user(self, username, email, password, **extra_fields):
        if not email:
            raise ValueError('PROVIDE A PROPER EMAIL!')
        if not username:
            raise ValueError('PROVIDE A USERNAME!')
        email = self.normalize_email(email)
        user = self.model(email=email,username=username, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError("Superuser must have is_staff=True")
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        return self.create_user(username, email, password, **extra_fields)

class UserExtendedR(AbstractBaseUser, PermissionsMixin):
    class Meta:
        verbose_name_plural = "users"
        verbose_name = "user"
    email = models.EmailField('email address', unique=True)
    username = models.CharField('username', max_length=25, unique=True)
    aboutme = models.CharField('bio', max_length=200, null=True)
    avatar = models.ImageField('avatar', blank=True, null=True, upload_to='images/')
    date_joined = models.DateField('date joined',default=timezone.now)
    post_liked = models.ManyToManyField('status.Post', null=True, blank=True)
    is_active = models.BooleanField('is active', default=True)
    is_staff = models.BooleanField('is staff', default=False)
    is_superuser = models.BooleanField('is superuser', default=False)
    following = models.ManyToManyField('self', through=FollowContact, related_name='followers', symmetrical=False)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    objects = UserExtendedManager()

    def __str__(self):
        return "{}".format(self.username)

    def get_short_name(self):
        return self.username

    def get_long_name(self):
        return self.username

userm/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import admin
from django.contrib.auth import get_user_model
from .models import UserExtendedR

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserEditForm(forms.models.ModelForm):
    class Meta:
        model = UserExtendedR
        fields = ('username', 'avatar', 'aboutme')
        widgets = {
            'aboutme': forms.Textarea,
        }

    
class UserSignUpForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

class UserChangeFormR(admin.UserChangeForm):
    class Meta:
        fields = '__all__'

class UserCreationFormR(admin.UserCreationForm):
    class Meta:
        fields = '__all__'

userm/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse, HttpResponseNotFound
from django.contrib.auth import authenticate, login, settings, get_user_model, logout
from django.db.models import Model
from django.views.generic.detail import DetailView 
from django.contrib.auth.decorators import login_required

from .forms import LoginForm, UserSignUpForm, UserEditForm
from .models import UserExtendedR, FollowContact

def user_login(request):
    if(request.method == 'POST'):
        form = LoginForm(request.POST)
        if(form.is_valid()):
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('status:index')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'userm/login.html', {'form': form})

def user_signup(request):
    if(request.method == 'POST'):
        form = UserSignUpForm(request.POST)
        if(form.is_valid()):
            cd = form.cleaned_data
            if cd['password1'] == cd['password2']:
                user = authenticate(username=cd['username'],
                                password=cd['password1'],
                                email=cd['email'])
                if user is None:
                    try:
                        UserExtendedR.objects.get(username=cd['username'])
                    except(KeyError, UserExtendedR.DoesNotExist):
                        try:
                            UserExtendedR.objects.get(email=cd['email'])
                        except(KeyError, UserExtendedR.DoesNotExist):
                            username = cd['username']
                            password1 = cd['password1']
                            password2 = cd['password2']
                            email = cd['email']
                            user = UserExtendedR.objects.create_user(username=username, email=email, password=password1)
                            return HttpResponse('User created successfully!')
                        else:
                            return HttpResponse('This email id is already registered!')
                    else:
                        return HttpResponse('Someone else has already taken the ID!')
            else:
                return HttpResponse('The passwords do not match!')
    else:
        form = UserSignUpForm()
    return render(request, 'userm/signup.html', {'form': form})

def user_details(request, username):
    try:
        usera = UserExtendedR.objects.get(username=username)
    except(KeyError, UserExtendedR.DoesNotExist):
        return HttpResponse('User does not exist!')
    else:
        if request.user.is_authenticated:
            try:
                con = FollowContact.objects.get(user_from=request.user, user_to=usera)
            except(KeyError, FollowContact.DoesNotExist):
                contact = False
            else:
                contact = True
        else:
            contact = False
        context = {
            'usera' : usera,
            'user' : request.user, 
            'show': request.user.is_authenticated and usera != request.user,
            'contact': contact,
        }
        return render(request, 'userm/details.html', context=context)

@login_required(login_url='/userm/login')
def edit_user(request):
    if not request.user.is_authenticated:
        return HttpResponse("You must be logged in to do that!")
    user = request.user
    if request.method == 'POST':
        form = UserEditForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            cd = form.cleaned_data
            try:
                user_c = UserExtendedR.objects.get(username=cd['username'])
            except(KeyError, UserExtendedR.DoesNotExist):
                request.user.username = cd['username']
                request.user.avatar = cd['avatar']
                request.user.aboutme = cd['aboutme']
                request.user.save()
                return HttpResponse("Successfully done!")
            else:
                if request.user == user_c:
                    request.user.username = cd['username']
                    request.user.avatar = cd['avatar']
                    request.user.aboutme = cd['aboutme']
                    request.user.save()
                    return HttpResponse("Successfully edited!")
                else:
                    return HttpResponse("That username has already been taken!")
    else:
        form = UserEditForm(instance=user)
    context = {
        'user' : user,
        'form' : form
    }
    return render(request, 'userm/edit.html', context=context)

@login_required(login_url='/userm/login')
def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('status:index')

@login_required(login_url='/userm/login')
def friend(request, user, user2):
    try:
        user1 = UserExtendedR.objects.get(username=user)
        user22 = UserExtendedR.objects.get(username=user2)
    except(KeyError, UserExtendedR.DoesNotExist):
        return HttpResponseNotFound('The user was not found')
    else:
        try:
            follower = FollowContact.objects.get(user_from=user22, user_to=user1)
        except(KeyError, FollowContact.DoesNotExist):
            follower = FollowContact(user_from=user22, user_to=user1)
            follower.save()
        else:
            return HttpResponse("You are already following him")
    return redirect('user:user', user)

@login_required(login_url='/userm/login')
def unfriend(request, user, user2):
    try:
        user1 = UserExtendedR.objects.get(username=user)
        user22 = UserExtendedR.objects.get(username=user2)
    except(KeyError, UserExtendedR.DoesNotExist):
        return HttpResponseNotFound('The user was not found')
    else:
        try:
            follower = FollowContact.objects.get(user_from=user22, user_to=user1)
            follower.delete()
        except(KeyError, FollowContact.DoesNotExist):
            return HttpResponseNotFound("You weren't following him")
    return redirect('user:user', user)

userm/templates/userm/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" href="{% static 'shop/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/open-iconic-bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/open-iconic-bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/open-iconic.css' %}">
        <link rel="stylesheet" href="{% static 'shop/font.css' %}">
        <link rel="stylesheet" href="{% static 'shop/main.css' %}">
        <script src="{% static 'shop/bootstrap.min.js' %}"></script>
        {% block imports %} {% endblock imports%}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <div class="page-header">
            <h1><a href="{% url 'status:index' %}">Project Genesis</a></h1>
        </div>
        {% block navbar %}
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Profile</a></li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                        {% else %}  
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        {% endblock navbar %}
         <div class="content container">
            <div class="row">
                <div class="col-md-10">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

userm/templates/userm/details.html
{% extends "userm/base.html" %}
{% load static %}

{% block title %}Project Genesis/User Details{% endblock %}

{% block imports %}
    <link rel="stylesheet" href="{% static 'css/details.css' %}">
{% endblock imports %}

{% block navbar %}
            <nav class="navbar navbar-expand-md navbar-dark" style="background-color:rgb(91, 90, 95);">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Profile</a></li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                        {% else %}  
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        {% endblock navbar %}

{% block content %}
    <h1 class="details-username">{{usera.username}}</h1>
    <br />
    <div class="details-avatar">
        {% if not usera.avatar %}
        <h3> The user doesn't have any image</h3>
        {% else %}
        <img src="{{ usera.avatar.url }}" alt="{{usera.username}}" height=300 width=400>
        {% endif %}
    </div>
    <br />
    <div class="details-bio">
        Bio: {{ user.aboutme | linebreaksbr}}
    </div>
    {% if show %}
    {% if not contact %}
        <a href="{% url 'user:friend' user.username request.user.username %}" class="btn btn-info" role="button">Follow</a> 
    {% else %}
        <a href="{% url 'user:unfriend' user.username request.user.username %}" class="btn btn-info" role="button">Unfollow</a>
    {% endif %}
    {% endif %}
{% endblock %}

userm/templates/userm/edit.html
{% extends "userm/base.html" %}
{% block title %} Project Genesis/Edit User{% endblock %}

{% block navbar %}
            <nav class="navbar navbar-expand-md navbar-dark" style="background-color:rgb(91, 90, 95);">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'user:edit' %}">Profile</a>
                            </li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                        {% else %}  
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
{% endblock navbar %}

{% block content %}
            <h3>Edit User Details:</h3>
            <div class="edit">
                <form method="post" action="." enctype="multipart/form-data">
                    <table border=0>
                    {{ form.as_table }}
                    {% csrf_token %}
                    <table>
                    <tr>
                        <input type="submit" class="btn btn-custom" value="Accept Changes" />
                    </tr>
                </form>
            </div>
{% endblock %}

userm/templates/userm/login.html
{% extends "userm/base.html" %}
{% load static %}

{% block title %}Project Genesis/Login{% endblock title%}</title>
{% block imports %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock imports %}

{% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark" style="background-color:rgb(91, 90, 95);">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Profile</a></li>
                {% endif %}
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                {% else %}  
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                        <li class="nav-item active"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock navbar %}

{% block content %}
    <h1 style="padding-bottom:10px;" class="heading">Log in</h1>
    <div class="login-form">
        <form action="." method="post">
            <table border=0>
                {{ form.as_table }}
                {% csrf_token %}
            <tr>
                <td colspan=2 align="center"><input type="submit" class="btn btn-custom" value="Login"></td>
            </tr>
            </table>
        </form>
    </div>
{% endblock content %}

userm/templates/userm/signup.html
{% extends "userm/base.html" %}
{% load static %}
{% block title %}Project Genesis/Login{% endblock title %}

{% block imports %}
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock imports %}

{% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark" style="background-color:rgb(91, 90, 95);">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Profile</a></li>
                {% endif %}
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                {% else %}  
                        <li class="nav-item active"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock navbar %}

{% block content %}
<h1>Sign Up</h1>
<p>Use the following form to signup:</p>
<form action="." method="post" class="signup">
    <table border=0>
        {{ form.as_table }}
        {% csrf_token %}
        <tr>
            <td colspan=2><input type="submit" class="btn btn-custom" value="Signup" style="padding-left:20px;padding-right:20px;margin-left:100px"></td>
        </tr>
    </table>
</form>
{% endblock content %}