prjgenesis/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('status/', include('status.urls')),
    path('userm/',include('userm.urls')),
    path('shop/', include('shop.urls')),
    path('', views.redirect_status)
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = "shop" 
urlpatterns = [
    path('', views.index, name='index'),
    path('list/<str:category_slug>/', views.product_list, name='list'),
    path('detail/<int:id>/<str:slug>/', views.product_detail, name="detail"),
    path('payment/<int:id>/<str:slug>/', views.payment, name="payment"),
    path('success/', views.success, name="success"),
    path('search/', views.search, name='search'),
]

status/urls.py
from django.urls import path, include
from . import views

app_name = 'status'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/', views.send, name='post'),
    path('users/<str:username>/', views.user, name='user'),
    path('details/<int:no>/', views.details, name='details'),
    path('replyto/<int:no>/',views.replyto, name='replyto'),
    path('like/<int:id>/', views.like, name='like'),
    path('unlike/<int:id>/', views.unlike, name='unlike'),
    path('contact/', views.contact, name='contact'),
    path('feed/', views.feed, name='feed'),
    path('search/', views.search, name='search'),
    path('help/',views.help, name='help')
]

userm/urls.py
from django.urls import path

from . import views

app_name="user"
urlpatterns = [
    path('login/',views.user_login, name='login'),
    path('signup/', views.user_signup, name='signup'),
    path('user/<str:username>', views.user_details, name='user'),
    path('edit/', views.edit_user, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('friend/<str:user>/<str:user2>', views.friend, name='friend'),
    path('unfriend/<str:user>/<str:user2>', views.unfriend, name='unfriend'),
]

shop/models.py
from django.db import models
from django.shortcuts import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:list', args=[self.slug])

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default="Item", null=False, blank=False, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    seller = models.ForeignKey('userm.UserExtendedR', on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:detail", args=[self.pk, self.slug])
    

class Photo(models.Model):
    photo = models.ImageField(upload_to='shop/', blank=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

shop/forms.py
from django import forms
from .models import Category

class ItemForm(forms.Form):
    name = forms.CharField()
    slug = forms.SlugField()
    category = forms.ChoiceField(choices=[(x, x.name) for x in Category.objects.all()])
    description = forms.CharField(widget=forms.Textarea)
    price = forms.DecimalField()
    stock = forms.IntegerField()
    main_image = forms.ImageField()

class FakePaymentForm(forms.Form):
    name = forms.CharField()
    address = forms.CharField(widget=forms.Textarea)
    pay_method = forms.ChoiceField(choices=[('Cash', 'Cash On Delivery'), ('Card', 'Credit/Debit Card'), ('IB', 'Intenet Banking')])
    card = forms.ChoiceField(choices=[('Mastercard', "MasterCard"), ('AmEx', "American Express"), ('Visa', "Visa Card")], required=False, widget=forms.HiddenInput)
class AddImageForm(forms.Form):
    image = forms.ImageField()

shop/views.py
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404, redirect
from django.core.files import File
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .models import *
from .forms import *
from urllib.parse import urlencode

def index(request):
    if request.method == 'POST':
        if search_handle(request):
            print("Reaching here!")
            return search_handle(request)
    categories = Category.objects.all()
    return render(request, 'shop/index.html', context={'user':request.user, 'categories': categories})

def search_handle(r):
    if 'searchb' in r.POST:
        text = r.POST['text']
        typ = r.POST['type']
        if text != "": 
            base_url = reverse('shop:search')
            query_string = urlencode({'type': typ,'name': text })
            return redirect("{}?{}".format(base_url, query_string))
    return False

def search(request):
    if request.method == 'POST':
        if search_handle(request):
            return search_handle(request)
    if request.method == 'GET' and 'type' in request.GET and 'name' in request.GET:
        search_type = request.GET.get('type', None)
        search_option = request.GET.get('name', None)
        print(search_type)
        print(search_option)
        if(search_type == '3'):
            items = Item.objects.filter(name__icontains=search_option)
            context = {
                'items': items,
                'user': request.user
            }
        else:
            return HttpResponseNotFound('This search type does not exist')
    else:
        context = {
            'user': request.user
        }
    return render(request, 'shop/search.html', context=context)

def product_list(request, category_slug=None):
    if request.method == 'POST':
        if search_handle(request):
            print("Reaching here!")
            return search_handle(request)
    category=None
    categories = Category.objects.all()
    prod = Item.objects.filter(available=True)
    user= request.user
    if category_slug is not None:
        print(category_slug)
        category = get_object_or_404(Category, slug=category_slug)
        prod = prod.filter(category=category)
        paginator = Paginator(prod, 10)
        page = request.GET.get('page')
        products = paginator.get_page(page)
    return render(request, 'shop/list.html', {
        'category': category,
        'categories': categories,
        'products':  products,
        'user': user})

def product_detail(request, id, slug):
    if request.method == 'POST':
        if search_handle(request):
            print("Reaching here!")
            return search_handle(request)
    form = AddImageForm()
    user = request.user
    categories = Category.objects.all()
    product = get_object_or_404(Item, id=id, slug=slug)
    if user.is_authenticated and user == product.seller and request.method == 'POST':
        form = AddImageForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            photo = Photo(photo=cd['image'], item=product)
            photo.save()
    return render(request, 'shop/detail.html', {'product': product, 'user': user, 'categories' : categories, 'form': form})

def success(request):
    if request.method == 'POST':
        if search_handle(request):
            print("Reaching here!")
            return search_handle(request)
    categories = Category.objects.all()
    return render(request, 'shop/success.html', context={'user': request.user, 'categories': categories})

@login_required(login_url='/userm/login')
def payment(request, id, slug):
    if request.method == 'POST':
        if search_handle(request):
            print("Reaching here!")
            return search_handle(request)
    form = FakePaymentForm()
    user =request.user
    categories = Category.objects.all()
    product = get_object_or_404(Item, id=id, slug=slug)
    if user.is_authenticated:
        if request.method == 'POST':
            form = FakePaymentForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                print("Payment succeeded")
                print("Name:", cd['name'])
                print("Address:", cd['address'])
                print("Payment Method:", cd['pay_method'])
                return redirect("shop:success")
    else:
        return HttpResponse('You must be logged in to do that!')

    return render(request, 'shop/payment.html', {'product': product, 'user': user, 'categories': categories, 'form': form})

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" href="{% static 'shop/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/open-iconic-bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/open-iconic-bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/open-iconic.css' %}">
        <link rel="stylesheet" href="{% static 'shop/font.css' %}">
        <link rel="stylesheet" href="{% static 'shop/main.css' %}">
        <script src="{% static 'shop/bootstrap.min.js' %}"></script>
        {% block imports %} {% endblock imports%}
        <title>{% block title %}{% endblock %}</title>
        <script>
            function openNav() {
                document.getElementById("mySidenav").style.width = "200px";
            }
            function closeNav() {
                document.getElementById("mySidenav").style.width = "0";
            }
        </script>
    </head>
    <body>
        <div class="page-header">
            <h1><a href="{% url 'status:index' %}">Project Genesis</a></h1>
            <form action="." method="post" autocomplete="off" onsubmit="validate()" name="search">
                {% csrf_token %}
                <div class="form-row align-items-center justify-content-center" style="font-family: 'Blinker', sans-serif;">
                    <div class="col-md-6">
                        <input type="text" class="form-control" placeholder="Search for items." name="text">
                    </div>
                    <div class="col-auto">
                        <select class="custom-select custom-select" name="type">
                            <option selected value="3">Products</option>
                        </select>
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-outline-dark btn-dark" name="searchb">
                            Search <span class="oi oi-magnifying-glass" title="icon magnifying-glass" aria-hidden="true"></span>
                        </button>
                    </div>
                </div></div>
            </form>
        </div>
        {% block navbar %}
            <nav class="navbar navbar-expand-md navbar-dark" style="background-color:rgb(132, 131, 136);">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" onclick="openNav()" style="cursor:pointer;"><span class="io io-list" ></span>Category</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Profile</a></li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                        {% else %}  
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        {% endblock navbar %}
        {% block sidebar %}
        {% endblock sidebar %}
         <div class="content container">
            <div class="row">
                <div class="col-md-10">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

shop/templates/shop/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load filters %}

{% block title %}
Project Genesis/Details{% if product %}/{{ product.name }}{% endif %}
{% endblock title %}

{% block imports %}
    <link rel="stylesheet" href="{% static 'shop/details.css' %}" >
{% endblock imports %}

{% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" onclick="openNav()" style="cursor:pointer;"><span class="oi oi-menu" title="icon menu" aria-hidden="true"></span>Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Profile</a></li>
                {% endif %}
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                {% else %}  
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock navbar %}

{% block sidebar %}
<div id="mySidenav" class="sidebar">
        <span style="font-size:2em;float:none;">Categories</span>&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><span class="oi oi-x" title="icon x" aria-hidden="true"></span></a>
        <ul class="cat">
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{%endif%} style="font-size=1.6em;">
                    <a class="cat" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
</div>
{% endblock sidebar %}

{% block content %}
    <div class="product-detail">
        <img src="{% if product|first_image %}{{ product|first_image }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
        <div class="details">
            <h1 class="title">{{product.name}}</h1>
            <h3><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h3>
            <p class="price">{{ product.price }}</p>
            <p class="desc">{{ product.description }}</p>
        </div>
        <div class="photos">
            {% for photo in product.photo_set.all %}
                <div class="photo">
                    <a href="{{ photo.photo.url }}"><img src="{{ photo.photo.url }}"></a>
                </div>
            {% endfor %}
        </div><br /><br /> <br /> <br /> <br />
        {% if user == product.seller %}
            <p><form method="post" action="." enctype="multipart/form-data">
                <table border=0>
                    {% csrf_token %}
                    {{form.as_table}}
                    <tr>
                        <td colspan=2><input type="submit" class="btn btn-custom" value="Add"></td>
                    </tr>
                </table>
            </form></p>
        {% else %}
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a class="btn btn-custom" href="{% url 'shop:payment' product.id product.slug%}">Buy</a>
        {% endif %}
    </div>
{% endblock content %}

shop/templates/shop/index.html
{% extends "shop/base.html" %}
{% load static %}
{% block title%}Project Genesis/Shop Index{% endblock title%}

{% block imports %}
<link rel="stylesheet" href="{% static 'shop/index.css' %}" >
{% endblock imports %}

{% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark" style="background-color:rgb(91, 90, 95);">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                </li>
                {% endif %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Profile</a></li>
                {% endif %}
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                {% else %}  
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock navbar %}

{% block sidebar %}
<div id="mySidenav" class="sidebar">
        <span style="font-size:2em;">Categories</span>&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><span class="glyphicon glyphicon-remove"></span></a>
        <ul>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{%endif%} style="font-size=1.6em;">
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
</div>
{% endblock sidebar %}

{% block content %}
    <h1 class="title">Welcome to the Project Genesis Shop</h1>
    <p style="font-size:1.2em;padding-bottom:10px;">Here you can find various items being sold by your favourite 
    artists, companies, youtubers etc. This site is was built to 
    promote an easy way of communication as not a lot of people will now 
    a person is selling some item unless they directly follow him on twitter, 
    facebook etc.</p>
    <h1 class="title">Our categories:</h1>
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'shop:list' category.slug %}">{{category.name}}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

shop/templates/shop/list.html
{% extends "shop/base.html" %}
{% load static %}
{% load filters %}

{% block title %}Project Genesis/Shop List{% if category %}/ {{category.name}}{% endif %}{% endblock title %}</title>

{% block imports %}
    <link rel="stylesheet" href="{% static 'shop/list.css' %}" >
{% endblock imports %}

{% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark" style="background-color:rgb(91, 90, 95);">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" onclick="openNav()" style="cursor:pointer;"><span class="oi oi-menu" title="icon menu" aria-hidden="true"></span>Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Profile</a></li>
                {% endif %}
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                {% else %}  
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock navbar %}

{% block sidebar %}
<div id="mySidenav" class="sidebar">
        <span style="font-size:2em;float:none;">Categories</span>&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><span class="oi oi-x" title="icon x" aria-hidden="true"></span></a>
        <ul class="cat">
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{%endif%} style="font-size=1.6em;">
                    <a class="cat" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
</div>
{% endblock sidebar %}



{% block content %}
    <div class="product-list">
        <h1 class="title">{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}"><img src="{% if product|first_image %}{{ product|first_image }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="image"></a>
                <h3>
                    <div id="title" style="float:left;">
                        Name: <a href="{{ product.get_absolute_url }}">{{product.name}}</a>
                    </div>
                </h3><br>
                <h4>
                    <div id="title" style="float:left;">
                        By: <a href="{% url 'user:user' product.seller %}" >{{product.seller}}</a>
                    </div>
                </h4><br>
                <h5><div id="price" style="float:left;">{{ product.price }}</div></h5><br>
            </div>
        {% endfor %}
    </div>
    {% if contacts.has_previous %}
        <span class="previous" style="float:left;display:block;padding:10px;margin:1px;margin-bottom:30px">
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ products.previous_page_number }}">previous</a>
        </span>
    {% endif %}
    <span class="current" style="float:left;display:block;padding:10px;margin:1px;margin-bottom:30px">
        Page {{ products.number }} of {{ products.paginator.num_pages }}.
    </span>
    {% if contacts.has_previous %}
        <span class="next" style="float:left;display:block;padding:10px;margin:1px;margin-bottom:30px">
            <a href="?page={{ products.next_page_number }}">next</a>
            <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
        </span>
    {% endif %}
{% endblock content %}

shop/templates/shop/payment.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}Project Genesis/Payment{% endblock title %}

{% block imports %}
    <link rel="stylesheet" href="{% static 'shop/payment.css' %}">
{% endblock imports %}

{% block sidebar %}
<div id="mySidenav" class="sidebar">
        <span style="font-size:2em;float:none;">Categories</span>&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><span class="oi oi-x" title="icon x" aria-hidden="true"></span></a>
        <ul class="cat">
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{%endif%} style="font-size=1.6em;">
                    <a class="cat" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
</div>
{% endblock sidebar %}

{% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark" style="background-color:rgb(91, 90, 95);">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:index' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:user' user.username %}">Your Statuses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'status:feed' %}">Status Feed</a>
                </li>
                {% endif %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'user:edit' %}">Profile</a></li>
                {% endif %}
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}"><span class="oi oi-account-logout" title="icon account-logout" aria-hidden="true"></span>&nbspLogout</a></li>
                {% else %}  
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:signup' %}"><span class="oi oi-person" title="icon person" aria-hidden="true"></span>&nbspSign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}"><span class="oi oi-account-login" title="icon account-login" aria-hidden="true"></span>&nbspLogin</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock navbar %}

{% block content %}
    <h1 class="title">Payment</h1>
    <h3 class="title">{{product.name}}</h3>
    <form method="post" action=".">
        <table border=0>
            {{ form.as_table }}
            {% csrf_token %}
            <tr>
                <td colspan=2><input type="submit" class="btn btn-custom" value="Confirm Payment"></td>
            </tr>
        </table>
    </form>
{% endblock content %}